<def f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='57' ll='59' type='void boost::container::exception::exception(const char * msg)'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='73' u='c' c='_ZN5boost9container9bad_allocC1Ev'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='84' u='c' c='_ZN5boost9container12out_of_rangeC1EPKc'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='95' u='c' c='_ZN5boost9container12length_errorC1EPKc'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='106' u='c' c='_ZN5boost9container11logic_errorC1EPKc'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='117' u='c' c='_ZN5boost9container13runtime_errorC1EPKc'/>
<doc f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='56'>//msg must be a static string (guaranteed by callers)</doc>
