<def f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='557' ll='562' type='exception_detail::clone_impl&lt;T&gt; boost::enable_current_exception(const T &amp; x)'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/detail/exception_ptr.hpp' l='67' u='c' c='_ZN5boost16exception_detail18wrap_exception_ptrERKNSt15__exception_ptr13exception_ptrE'/>
