<dec f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='234' type='const E &amp; boost::exception_detail::set_info(const E &amp; , const boost::throw_function &amp; )'/>
<dec f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='293' type='const E &amp; boost::exception_detail::set_info(const E &amp; , const boost::throw_function &amp; )'/>
<def f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='342' ll='347' type='const E &amp; boost::exception_detail::set_info(const E &amp; x, const boost::throw_function &amp; y)'/>
