<dec f='boost-1.85.0/libs/log/include/boost/log/exceptions.hpp' l='226' type='void boost::log::invalid_value::~invalid_value()'/>
<doc f='boost-1.85.0/libs/log/include/boost/log/exceptions.hpp' l='223'>/*!
     * Destructor
     */</doc>
<inh f='boost-1.85.0/libs/log/src/exceptions.cpp' l='116' c='_ZN5boost3log12v2s_mt_posix13runtime_errorD1Ev'/>
<def f='boost-1.85.0/libs/log/src/exceptions.cpp' l='280' ll='282' type='void boost::log::invalid_value::~invalid_value()'/>
