<def f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='46' ll='49' type='void boost::exception_detail::refcount_ptr::refcount_ptr&lt;T&gt;()'/>
<use f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='493' u='c' c='_ZN5boost16exception_detail20copy_boost_exceptionEPNS_9exceptionEPKS1_'/>
<use f='boost-1.85.0/libs/exception/include/boost/exception/info.hpp' l='144' u='c' c='_ZNK5boost16exception_detail25error_info_container_impl5cloneEv'/>
