<def f='boost-1.85.0/libs/wave/include/boost/wave/cpplexer/cpplexer_exceptions.hpp' l='274' ll='278' type='bool boost::wave::cpplexer::is_recoverable(const boost::wave::cpplexer::lexing_exception &amp; e)'/>
<doc f='boost-1.85.0/libs/wave/include/boost/wave/cpplexer/cpplexer_exceptions.hpp' l='265'>///////////////////////////////////////////////////////////////////////////////
//
//  The is_recoverable() function allows to decide, whether it is possible
//  simply to continue after a given exception was thrown by Wave.
//
//  This is kind of a hack to allow to recover from certain errors as long as
//  Wave doesn&apos;t provide better means of error recovery.
//
///////////////////////////////////////////////////////////////////////////////</doc>
