<def f='include/c++/9/bits/exception.h' l='63' type='void std::exception::exception()'/>
<use f='boost-1.85.0/libs/container/include/boost/container/throw_exception.hpp' l='58' u='c' c='_ZN5boost9container9exceptionC1EPKc'/>
