<inh f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='20' c='boost::future_error'/>
<def f='boost-1.85.0/libs/thread/include/boost/thread/futures/future_error.hpp' l='45' ll='52'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='2316' c='_ZN5boost7promiseD1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='2607' c='_ZN5boost7promiseIRT_ED1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='2788' c='_ZN5boost7promiseIvED1Ev'/>
<use f='boost-1.85.0/libs/thread/include/boost/thread/future.hpp' l='3029' c='_ZN5boost6detail22task_base_shared_state15owner_destroyedEv'/>
<size>40</size>
<fun r='_ZN5boost14broken_promiseC1Ev'/>
