<inh f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='250' c='boost::exception'/>
<def f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='408' ll='423'/>
<use f='boost-1.85.0/libs/throw_exception/include/boost/exception/exception.hpp' l='445'/>
<fun r='_ZN5boost16exception_detail19error_info_injectorC1ERKT_'/>
<fun r='_ZN5boost16exception_detail19error_info_injectorD1Ev'/>
