<def f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='49' ll='57'/>
<ovr f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='82' c='boost::contract::bad_virtual_result_cast'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='83'/>
<ovr f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='137' c='boost::contract::assertion_failure'/>
<use f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='138'/>
<size>8</size>
<doc f='boost-1.85.0/libs/contract/include/boost/contract/core/exception.hpp' l='38'>/**
Public base class for all exceptions directly thrown by this library.

This class does not inherit from @c std::exception because exceptions deriving
from this class will do that (inheriting from @c std::exception,
@c std::bad_cast, etc.).

@see    @RefClass{boost::contract::assertion_failure},
        @RefClass{boost::contract::bad_virtual_result_cast},
        etc.
*/</doc>
<fun r='_ZN5boost8contract9exceptionD1Ev'/>
<fun r='_ZN5boost8contract9exceptionD1Ev'/>
