<dec f='qtbase-6.5.0/src/network/socket/qlocalsocket.h' l='38' type='7'/>
<use f='qtbase-6.5.0/src/network/socket/qlocalsocket.cpp' l='564' c='_Zls6QDebugN12QLocalSocket16LocalSocketErrorE'/>
<doc f='qtbase-6.5.0/src/network/socket/qlocalsocket.cpp' l='515'>\value ConnectionError An error occurred with the connection.
    </doc>
<use f='qtbase-6.5.0/src/network/socket/qlocalsocket_unix.cpp' l='145' c='_ZNK19QLocalSocketPrivate19generateErrorStringEN12QLocalSocket16LocalSocketErrorERK7QString'/>
<use f='qtbase-6.5.0/src/network/socket/qlocalsocket_unix.cpp' l='186' c='_ZN19QLocalSocketPrivate15setErrorAndEmitEN12QLocalSocket16LocalSocketErrorERK7QString'/>
<use f='qtbase-6.5.0/src/network/socket/qlocalsocket_unix.cpp' l='549' u='r' c='_ZNK12QLocalSocket5errorEv'/>
